import type { Metadata } from "next";
import { poppins, poppins_Mono } from "next/font/google";
import "./globals.css";

const poppinsSans = poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
});

const poppinsMono = poppins_Mono({
  variable: "--font-poppins-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsSans.variable} ${poppinsMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
