import type { Metadata } from "next";

// NOTE:
// Font & <html>/<body> ditetapkan di app/layout.tsx agar konsisten di seluruh aplikasi.
// Layout dashboard cukup me-render children saja.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return children;
}
